@startsalt
{
Новый сотрудник
ФИО | "Иванов Иван Иванович"
Должность | ^инженеры^
Отдел | ^Конструкторский отдел^
Пол | { (X) М | () Ж }
Адрес | "г. Архангельск, ул. Ленина, 1"
Дата рождения | "15.04.1990"
[Отмена] | [Сохранить]
}
@endsalt
