@startsalt
{
Договоры
{#
Номер | Дата заключения | Организация | Стоимость
1 | 12.03.2024 | ООО "Север" | 150000.00
2 | 20.05.2024 | АО "Двина" | 320000.00
3 | 01.09.2024 | ООО "Помор" | 85000.00
}
{ Поиск: | "          " | [Найти] }
{ [Добавить] | [Изменить] | [Удалить] | [Назад] }
}
@endsalt
