@startsalt
{
{+
Отделы
1. Показать отделы
2. Добавить новый отдел
3. Изменить данные отдела
4. Удалить отдел
5. Поиск отдела
0. Назад
"Введите выбранный номер:"
} | {+
Сотрудники
1. Показать сотрудников
2. Добавить нового сотрудника
3. Изменить данные сотрудника
4. Удалить сотрудника
5. Поиск сотрудника
0. Назад
"Введите выбранный номер:"
} | {+
Организации
1. Показать организации
2. Добавить новую организацию
3. Изменить данные организации
4. Удалить организацию
5. Поиск организации
0. Назад
"Введите выбранный номер:"
}
{+
Договоры
1. Показать договоры
2. Добавить новый договор
3. Изменить данные договора
4. Удалить договор
5. Поиск договора
0. Назад
"Введите выбранный номер:"
} | {+
Проектные работы
1. Показать проектные работы
2. Добавить новую проектную работу
3. Изменить данные проектной работы
4. Удалить проектную работу
5. Поиск проектной работы
0. Назад
"Введите выбранный номер:"
}
}
@endsalt
