@startsalt
{
Администрирование
1. Показать пользователей
2. Добавить пользователя
3. Изменить пользователя
4. Удалить пользователя
5. Создать резервную копию
6. Восстановить из резервной копии
0. Назад
"Введите выбранный номер:"
}
@endsalt
