@startsalt
{
{+
Отделы
{#
Название отдела | Этаж | Телефон | Начальник отдела
Конструкторский отдел | 2 | 20-11-01 | Смирнов Алексей Петрович
Отдел проектирования | 3 | 20-11-02 | Кузнецова Ольга Игоревна
Лаборатория испытаний | 1 | 20-11-03 | Попов Дмитрий Сергеевич
}
{ Поиск: | "          " | [Найти] }
{ [Добавить] | [Изменить] | [Удалить] | [Назад] }
}
{+
Сотрудники
{#
ФИО | Должность | Отдел | Пол | Адрес | Дата рождения
Иванов Иван Иванович | конструкторы | Конструкторский отдел | М | г. Архангельск, ул. Ленина, 1 | 15.04.1990
Петрова Анна Сергеевна | инженеры | Отдел проектирования | Ж | г. Архангельск, пр. Троицкий, 10 | 02.08.1995
Сидоров Павел Андреевич | техники | Отдел проектирования | М | г. Северодвинск, ул. Морская, 5 | 23.11.1988
}
{ Поиск: | "          " | [Найти] }
{ [Добавить] | [Изменить] | [Удалить] | [Назад] }
}
{+
Организации
{#
Название организации | Тип деятельности | Страна | Город | Адрес | ФИО директора
ООО "Север" | строительство | Россия | Архангельск | ул. Гайдара, 4 | Орлов Виктор Николаевич
АО "Двина" | судостроение | Россия | Северодвинск | ул. Карла Маркса, 2 | Белова Ирина Павловна
ООО "Помор" | энергетика | Беларусь | Минск | пр. Независимости, 15 | Ковалёв Андрей Иванович
}
{ Поиск: | "          " | [Найти] }
{ [Добавить] | [Изменить] | [Удалить] | [Назад] }
}
{+
Договоры
{#
Номер | Дата заключения | Организация | Стоимость
1 | 12.03.2024 | ООО "Север" | 150000.00
2 | 20.05.2024 | АО "Двина" | 320000.00
3 | 01.09.2024 | ООО "Помор" | 85000.00
}
{ Поиск: | "          " | [Найти] }
{ [Добавить] | [Изменить] | [Удалить] | [Назад] }
}
{+
Проектные работы
{#
Дата начала | Дата завершения | Номер договора | Отдел
15.03.2024 | 30.06.2024 | 1 | Конструкторский отдел
25.05.2024 | — | 2 | Отдел проектирования
05.09.2024 | 20.12.2024 | 3 | Лаборатория испытаний
}
{ Поиск: | "          " | [Найти] }
{ [Добавить] | [Изменить] | [Удалить] | [Назад] }
}
}
@endsalt
