@startsalt
{
{+
Добавление / изменение: отдел
{
Название отдела | "Конструкторский отдел"
Этаж | "2         "
Телефон | "20-11-01  "
Начальник отдела | "Смирнов Алексей Петрович"
}
{ [Отмена] | [Сохранить] }
} | {+
Добавление / изменение: сотрудник
{
ФИО | "Иванов Иван Иванович"
Должность | ^инженеры^
Отдел | ^Конструкторский отдел^
Пол | { (X) М | () Ж }
Адрес | "г. Архангельск, ул. Ленина, 1"
Дата рождения | "15.04.1990"
}
{ [Отмена] | [Сохранить] }
}
{+
Добавление / изменение: организация
{
Название организации | "ООО «Север»        "
Тип деятельности | "строительство     "
Страна | "Россия    "
Город | "Архангельск"
Адрес | "ул. Гайдара, 4    "
ФИО директора | "Орлов Виктор Николаевич"
}
{ [Отмена] | [Сохранить] }
} | {+
Добавление / изменение: договор
{
Номер договора | "4         "
Дата заключения | "01.10.2024"
Организация | ^ООО "Север"^
Стоимость | "100000.00 "
}
{ [Отмена] | [Сохранить] }
}
{+
Добавление / изменение: проектная работа
{
Дата начала | "15.03.2024"
Дата завершения | "30.06.2024"
Договор | ^1^
Отдел | ^Конструкторский отдел^
}
{ [Отмена] | [Сохранить] }
}
}
@endsalt
