@startuml
start
:выбрать организацию;
:ввести новые данные;
if (подключиться к базе данных?) then (yes)
  :update organization set ...;
  :сохранить изменения;
  :закрыть подключение к базе данных;
  :показать сообщение "Данные изменены";
else (no)
  :показать сообщение об ошибке;
endif
stop
@enduml
