@startuml
actor       "Сотрудник организации" as U
control     Контроллер
boundary    Вид
entity      Отдел
entity      Сотрудник
entity      Организация
entity      Договор
entity      ПроектнаяРабота
database    "База данных"

U -> Вид : выбор раздела и "добавить"
Контроллер -> Вид : получить_данные()
return выбор пользователя
U -> Вид : ввод данных
Контроллер -> Вид : получить_данные()
return введённые данные
alt отделы
  Контроллер -> Отдел : добавить_данные_отдела()
  Отдел -> "База данных" : insert into department ...;
  return отдел добавлен
  Контроллер <-- Отдел : отдел добавлен
else сотрудники
  Контроллер -> Сотрудник : добавить_данные_сотрудника()
  Сотрудник -> "База данных" : insert into employee ...;
  return сотрудник добавлен
  Контроллер <-- Сотрудник : сотрудник добавлен
else организации
  Контроллер -> Организация : добавить_данные_организации()
  Организация -> "База данных" : insert into organization ...;
  return организация добавлена
  Контроллер <-- Организация : организация добавлена
else договоры
  Контроллер -> Договор : добавить_данные_договора()
  Договор -> "База данных" : insert into contract ...;
  return договор добавлен
  Контроллер <-- Договор : договор добавлен
else проектные работы
  Контроллер -> ПроектнаяРабота : добавить_данные_работы()
  ПроектнаяРабота -> "База данных" : insert into project_work ...;
  return проектная работа добавлена
  Контроллер <-- ПроектнаяРабота : проектная работа добавлена
end
Контроллер -> Вид : показать_сообщение()
U <-- Вид : "Запись добавлена"
@enduml
