@startuml
actor       "Менеджер по договорам" as U
control     Контроллер
boundary    Вид
entity      Организация
database    "База данных"

U -> Вид : выбор организации и "изменить"
Контроллер -> Вид : получить_данные()
return выбранная организация
U -> Вид : ввод новых данных
Контроллер -> Вид : получить_данные()
return новые данные организации
Контроллер -> Организация : изменить_данные_организации()
Организация -> "База данных" : update organization set ... where id = ...;
return данные изменены
Контроллер <-- Организация : данные изменены
Контроллер -> Вид : показать_сообщение()
U <-- Вид : "Данные изменены"
@enduml
