@startuml
actor       "Сотрудник организации" as U
control     Контроллер
boundary    Вид
database    "База данных"

U -> Контроллер : запуск()
Контроллер -> Вид : показать_окно_входа()
U <-- Вид : окно входа
U -> Вид : ввод логина и пароля
Контроллер -> Вид : получить_данные()
return логин и пароль
Контроллер -> "База данных" : подключение
return подключение выполнено
Контроллер -> Вид : показать_меню()
U <-- Вид : вывод меню
@enduml
