@startuml
actor       "Сотрудник организации" as U
control     Контроллер
boundary    Вид
entity      Отдел
entity      Сотрудник
entity      Организация
entity      Договор
entity      ПроектнаяРабота
database    "База данных"

U -> Вид : выбор записи и "удалить"
Контроллер -> Вид : получить_данные()
return выбранная запись
alt отделы
  Контроллер -> Отдел : удалить_данные_отдела()
  Отдел -> "База данных" : delete from department where id = ...;
  return отдел удалён
  Контроллер <-- Отдел : отдел удалён
else сотрудники
  Контроллер -> Сотрудник : удалить_данные_сотрудника()
  Сотрудник -> "База данных" : delete from employee where id = ...;
  return сотрудник удалён
  Контроллер <-- Сотрудник : сотрудник удалён
else организации
  Контроллер -> Организация : удалить_данные_организации()
  Организация -> "База данных" : delete from organization where id = ...;
  return организация удалена
  Контроллер <-- Организация : организация удалена
else договоры
  Контроллер -> Договор : удалить_данные_договора()
  Договор -> "База данных" : delete from contract where id = ...;
  return договор удалён
  Контроллер <-- Договор : договор удалён
else проектные работы
  Контроллер -> ПроектнаяРабота : удалить_данные_работы()
  ПроектнаяРабота -> "База данных" : delete from project_work where id = ...;
  return проектная работа удалена
  Контроллер <-- ПроектнаяРабота : проектная работа удалена
end
Контроллер -> Вид : показать_сообщение()
U <-- Вид : "Запись удалена"
@enduml
