@startuml
actor       Кадровик as U
control     Контроллер
boundary    Вид
entity      Сотрудник
database    "База данных"

U -> Вид : выбор в меню "добавить сотрудника"
Контроллер -> Вид : получить_данные()
return выбор пользователя
U -> Вид : ввод данных сотрудника
Контроллер -> Вид : получить_данные()
return данные сотрудника
Контроллер -> Сотрудник : добавить_данные_сотрудника()
Сотрудник -> "База данных" : insert into employee ...;
return сотрудник добавлен
Контроллер <-- Сотрудник : сотрудник добавлен
Контроллер -> Вид : показать_сообщение()
U <-- Вид : "Сотрудник добавлен"
@enduml
