@startuml
actor       "Сотрудник организации" as U
control     Контроллер
boundary    Вид
entity      Отдел
entity      Сотрудник
entity      Организация
entity      Договор
entity      ПроектнаяРабота
database    "База данных"

U -> Вид : выбор записи и "изменить"
Контроллер -> Вид : получить_данные()
return выбранная запись
U -> Вид : ввод новых данных
Контроллер -> Вид : получить_данные()
return новые данные
alt отделы
  Контроллер -> Отдел : изменить_данные_отдела()
  Отдел -> "База данных" : update department set ... where id = ...;
  return данные изменены
  Контроллер <-- Отдел : данные изменены
else сотрудники
  Контроллер -> Сотрудник : изменить_данные_сотрудника()
  Сотрудник -> "База данных" : update employee set ... where id = ...;
  return данные изменены
  Контроллер <-- Сотрудник : данные изменены
else организации
  Контроллер -> Организация : изменить_данные_организации()
  Организация -> "База данных" : update organization set ... where id = ...;
  return данные изменены
  Контроллер <-- Организация : данные изменены
else договоры
  Контроллер -> Договор : изменить_данные_договора()
  Договор -> "База данных" : update contract set ... where id = ...;
  return данные изменены
  Контроллер <-- Договор : данные изменены
else проектные работы
  Контроллер -> ПроектнаяРабота : изменить_данные_работы()
  ПроектнаяРабота -> "База данных" : update project_work set ... where id = ...;
  return данные изменены
  Контроллер <-- ПроектнаяРабота : данные изменены
end
Контроллер -> Вид : показать_сообщение()
U <-- Вид : "Данные изменены"
@enduml
