@startuml
actor       Исполнитель as U
control     Контроллер
boundary    Вид
entity      ПроектнаяРабота
database    "База данных"

U -> Вид : ввод текста в поле поиска
Контроллер -> Вид : получить_данные()
return текст поиска
Контроллер -> ПроектнаяРабота : показать_данные_работ()
ПроектнаяРабота -> "База данных" : select * from project_work where ... like ...;
return найденные работы
Контроллер <-- ПроектнаяРабота : найденные работы
Контроллер -> Вид : показать_данные()
U <-- Вид : вывод найденных работ
@enduml
