@startuml
actor       "Менеджер по договорам" as U
control     Контроллер
boundary    Вид
entity      Договор
database    "База данных"

U -> Контроллер : запуск()
Контроллер -> Вид : показать_меню()
U <-- Вид : вывод меню
U -> Вид : выбор в меню "показать договоры"
Контроллер -> Вид : получить_данные()
return выбор пользователя
Контроллер -> Договор : показать_данные_договоров()
Договор -> "База данных" : select * from contract;
return набор данных договоров
Контроллер <-- Договор : набор данных договоров
Контроллер -> Вид : показать_данные()
U <-- Вид : вывод договоров
@enduml
