@startuml
actor       "Сотрудник организации" as U
control     Контроллер
boundary    Вид
entity      Отдел
entity      Сотрудник
entity      Организация
entity      Договор
entity      ПроектнаяРабота
database    "База данных"

U -> Контроллер : запуск()
Контроллер -> Вид : показать_меню()
U <-- Вид : вывод меню
U -> Вид : выбор раздела и "показать"
Контроллер -> Вид : получить_данные()
return выбор пользователя
alt отделы
  Контроллер -> Отдел : показать_данные_отделов()
  Отдел -> "База данных" : select * from department;
  return набор данных отделов
  Контроллер <-- Отдел : набор данных отделов
else сотрудники
  Контроллер -> Сотрудник : показать_данные_сотрудников()
  Сотрудник -> "База данных" : select * from employee;
  return набор данных сотрудников
  Контроллер <-- Сотрудник : набор данных сотрудников
else организации
  Контроллер -> Организация : показать_данные_организаций()
  Организация -> "База данных" : select * from organization;
  return набор данных организаций
  Контроллер <-- Организация : набор данных организаций
else договоры
  Контроллер -> Договор : показать_данные_договоров()
  Договор -> "База данных" : select * from contract;
  return набор данных договоров
  Контроллер <-- Договор : набор данных договоров
else проектные работы
  Контроллер -> ПроектнаяРабота : показать_данные_работ()
  ПроектнаяРабота -> "База данных" : select * from project_work;
  return набор данных работ
  Контроллер <-- ПроектнаяРабота : набор данных работ
end
Контроллер -> Вид : показать_данные()
U <-- Вид : вывод записей
@enduml
