@startuml
actor       Кадровик as U
control     Контроллер
boundary    Вид
entity      Отдел
database    "База данных"

U -> Вид : выбор отдела и "удалить"
Контроллер -> Вид : получить_данные()
return выбранный отдел
Контроллер -> Отдел : удалить_данные_отдела()
Отдел -> "База данных" : delete from department where id = ...;
return отдел удалён
Контроллер <-- Отдел : отдел удалён
Контроллер -> Вид : показать_сообщение()
U <-- Вид : "Отдел удалён"
@enduml
