@startuml
[Приложение]

[База данных]

Приложение --> Отдел : use
Приложение --> Сотрудник : use
Приложение --> Организация : use
Приложение --> Договор : use
Приложение --> ПроектнаяРабота : use

Отдел -- [База данных]
Сотрудник -- [База данных]
Организация -- [База данных]
Договор -- [База данных]
ПроектнаяРабота -- [База данных]
@enduml
