@startuml
node "Сервер баз данных" as dbs {
component [База данных]
}
node "Рабочая станция" as ws {
component Приложение
artifact model.py
artifact controller.py
artifact view.py
Приложение <-- model.py
Приложение <-- controller.py
Приложение <-- view.py
}
dbs -- ws
@enduml
