@startchen
' ER-диаграмма в нотации Питера Чена

entity ОТДЕЛ {
  номер_отдела <<key>>
  название_отдела
  этаж
  телефон
  начальник_отдела
}

entity СОТРУДНИК {
  номер_сотрудника <<key>>
  фио
  должность
  пол
  адрес
  дата_рождения
}

entity ОРГАНИЗАЦИЯ {
  номер_организации <<key>>
  название_организации
  тип_деятельности
  страна
  город
  адрес
  фио_директора
}

entity ДОГОВОР <<weak>> {
  номер_договора <<key>>
  дата_заключения
  стоимость
}

entity ПРОЕКТНАЯ_РАБОТА <<weak>> {
  номер_работы <<key>>
  дата_начала
  дата_завершения
}

relationship РАБОТАЕТ_В {
}
relationship ЗАКЛЮЧАЕТ <<identifying>> {
}
relationship ВЫПОЛНЯЕТСЯ_ПО <<identifying>> {
}
relationship РАЗРАБАТЫВАЕТ {
}

ОТДЕЛ -1- РАБОТАЕТ_В
РАБОТАЕТ_В -N- СОТРУДНИК

ОРГАНИЗАЦИЯ -1- ЗАКЛЮЧАЕТ
ЗАКЛЮЧАЕТ =N= ДОГОВОР

ДОГОВОР -1- ВЫПОЛНЯЕТСЯ_ПО
ВЫПОЛНЯЕТСЯ_ПО =N= ПРОЕКТНАЯ_РАБОТА

ОТДЕЛ -1- РАЗРАБАТЫВАЕТ
РАЗРАБАТЫВАЕТ -N- ПРОЕКТНАЯ_РАБОТА
@endchen
